name: kasambahayko
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  get: ^4.6.6
  flutter_toggle_tab: ^1.4.1
  im_stepper: ^1.0.1+1
  carousel_slider: ^4.2.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  mysql1: ^0.20.0
  http: ^1.1.0
  dio: ^5.3.3
  flutter_image_compress: ^2.0.4
  conditional_builder_null_safety: ^0.0.6
  multiselect: ^0.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/region-viii.json
    - assets/data/region-viii-with-coordinates.json